### YamlMime:Lifecycle
metadata:
  title: Microsoft Intelligent Application Gateway 2007
  description: Microsoft Intelligent Application Gateway 2007 segue i Criteri fissi relativi al ciclo di vita.
  ms.date: 07/28/2020
  ms.openlocfilehash: 2e4cb68a2f1b63fbdc64507b9b16fbdc2f8008a0
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4114634"
name: Microsoft Intelligent Application Gateway 2007
summary: >
  Microsoft Intelligent Application Gateway 2007 segue i Criteri [fissi](/lifecycle/policies/fixed) relativi al ciclo di vita.



  > [!IMPORTANT]

  > Il supporto per questo prodotto è terminato. Vedere le linee guida per la migrazione riportate di seguito.
products:
- microsoft-servers
policyType: fixed
supportDates:
  start: 2007-06-01T00:00:00.000-08:00
  end: 2012-07-10T22:59:59.999-08:00
  extendedEnd: 2017-07-11T22:59:59.999-08:00
releases:
- version: Service Pack 2
  startDate: 2008-11-27T00:00:00.000-08:00
  endDate: 2017-07-11T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2007-09-03T00:00:00.000-08:00
  endDate: 2010-01-12T22:59:59.999-08:00
- version: Original Release
  startDate: 2007-06-01T00:00:00.000-08:00
  endDate: 2008-10-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Collegamenti \n* [Microsoft Intelligent Application Gateway 2007 Roadmap](/archive/blogs/testtesttestbug/important-changes-to-the-forefront-product-line)\n* [Criteri relativi ai Service pack](/lifecycle/policies/fixed#service-packs)"
