### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 5.1
  description: Microsoft Application Virtualization 5.1 segue i criteri fissi relativi al ciclo di vita.
  ms.date: 09/10/2020
  keywords: for Remote Desktop Services,for Windows Desktops
  ms.openlocfilehash: 5ebb28c8965d47f928547b36980e68ed6cc9c791
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4155704"
name: Microsoft Application Virtualization 5.1
summary: >+
  Microsoft Application Virtualization 5.1 segue i criteri [fissi](/lifecycle/policies/fixed) relativi al ciclo di vita.


  Questo vale per le seguenti edizioni: per Servizi Desktop remoto, per Windows Desktop

products:
- windows
policyType: fixed
supportDates:
  start: 2015-11-01T00:00:00.000-08:00
  end: 2018-01-09T22:59:59.999-08:00
  extendedEnd: 2026-04-14T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2015-11-01T00:00:00.000-08:00
  endDate: 2026-04-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Collegamenti \n* [Informazioni sul prodotto](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)\n\n\n## <a name=\"editions\"></a>Edizioni \n* per Servizi Desktop remoto\n* per Windows Desktop"
