### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 5.0
  description: Microsoft Application Virtualization 5.0 segue i Criteri fissi relativi al ciclo di vita.
  ms.date: 09/01/2020
  keywords: for Remote Desktop Services,for Terminal Services,for Windows Desktops
  ms.openlocfilehash: 9606d01862383fc90e328d1fe65da5151014db76
  ms.sourcegitcommit: af46dd09ccdabd80dcc49d2cd930cefa0b1ab8a6
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 09/01/2020
  ms.locfileid: "935528"
name: Microsoft Application Virtualization 5.0
summary: >+
  Microsoft Application Virtualization 5.0 segue i Criteri [fissi](/lifecycle/policies/fixed) relativi al ciclo di vita.


  Questo vale per le seguenti edizioni: per Servizi Desktop remoto, per Servizi terminal, per Windows Desktop

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2012
  end: 01/09/2018
  extendedEnd: 01/10/2023
releases:
- version: Service Pack 3
  startDate: 12/08/2014
  endDate: 01/10/2023
- version: Service Pack 2
  startDate: 12/02/2013
  endDate: 01/12/2016
- version: Service Pack 1
  startDate: 04/10/2013
  endDate: 01/13/2015
- version: Original Release
  startDate: 11/01/2012
  endDate: 07/08/2014
content: "\n## <a name=\"links\"></a>Collegamenti \n* [Informazioni sul prodotto](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)\n* [Criteri relativi ai Service pack](/lifecycle/policies/fixed#service-packs)\n\n\n## <a name=\"editions\"></a>Edizioni \n* per Servizi Desktop remoto\n* per Servizi terminal\n* per Windows Desktop"
