### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.6 per desktop Windows
  description: Microsoft Application Virtualization Hosting 4.6 per Desktop Windows segue i Criteri fissi relativi al ciclo di vita.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 3d5789104bc3b52d4ccfb836df52ddd2ab576d4e
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4153928"
name: Microsoft Application Virtualization Hosting 4.6 per desktop Windows
summary: >+
  Microsoft Application Virtualization Hosting 4.6 per Desktop Windows segue i Criteri [fissi](/lifecycle/policies/fixed) relativi al ciclo di vita.


  Questo vale per le seguenti edizioni: per Windows Desktop

products:
- windows
policyType: fixed
supportDates:
  start: 2010-05-27T00:00:00.000-08:00
  end: 2015-07-14T22:59:59.999-08:00
  extendedEnd: 2020-07-14T22:59:59.999-08:00
releases:
- version: Service Pack 3
  startDate: 2013-12-02T00:00:00.000-08:00
  endDate: 2020-07-14T22:59:59.999-08:00
- version: Service Pack 2
  startDate: 2012-10-01T00:00:00.000-08:00
  endDate: 2015-01-13T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2011-01-26T00:00:00.000-08:00
  endDate: 2013-10-08T22:59:59.999-08:00
- version: Original Release
  startDate: 2010-05-27T00:00:00.000-08:00
  endDate: 2012-04-10T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Collegamenti \n* [Informazioni sul prodotto e sulla migrazione](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Criteri relativi ai Service pack](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Poiché il client App-V 4.6 utilizza il server App-V 4.5, il server App-V 4.5 continuerà a essere supportato in base alle date del ciclo di vita di App-V 4.6 se in uso con il client App-V 4.6 supportato.\n\n## <a name=\"editions\"></a>Edizioni \n* per Windows Desktop"
