### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: Microsoft System Center Configuration Manager 2007 R3 segue i Criteri fissi relativi al ciclo di vita.
  ms.date: 07/28/2020
name: Microsoft System Center Configuration Manager 2007 R3
summary: |
  Microsoft System Center Configuration Manager 2007 R3 segue i Criteri [fissi](/lifecycle/policies/fixed) relativi al ciclo di vita. 


  > [!IMPORTANT]
  > Il supporto per questo prodotto è terminato. Vedere le linee guida per la migrazione riportate di seguito.
products:
  - msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
  - version: Original Release
    startDate: 12/19/2010
    endDate: 07/09/2019
content: |+

  ## <a name="links"></a>Collegamenti 
  * [Indicazioni sulla migrazione](/mem/configmgr/core/migration/migrate-data-between-hierarchies)
  * [Ulteriori indicazioni sulla migrazione](/mem/configmgr/core/migration/planning-for-migration)