### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security segue i criteri fissi relativi al ciclo di vita.
  ms.date: 08/28/2020
name: Microsoft Forefront Client Security
summary: |+
  Microsoft Forefront Client Security segue i [criteri fissi](/lifecycle/policies/fixed) relativi al ciclo di vita.


products:
  - msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
  - version: Original Release
    startDate: 08/02/2007
    endDate: 07/14/2015
content: |+

  ## <a name="links"></a>Collegamenti 
  * [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)

  > [!NOTE]
  > Forefront Client Securitynon è più disponibile a partire dal 14 luglio 2015. Gli aggiornamenti delle definizioni antimalware e antispyware non saranno più disponibili dopo la fine del supporto per la versione del prodotto. Valutare System Center Endpoint Protection come sostituzione.