### YamlMime:Lifecycle
metadata:
  title: SoftGrid Application Virtualization
  description: SoftGrid Application Virtualization segue il criterio del ciclo di vita fisso.
  ms.date: 07/28/2020
  ms.openlocfilehash: 17b8078138b718a634c2561ac4b1e73f3966ce24
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: it-IT
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "824122"
name: SoftGrid Application Virtualization
summary: >
  SoftGrid Application Virtualization segue il criterio del ciclo di vita [fisso](/lifecycle/policies/fixed) .


  Si applica alle edizioni seguenti: 4,1 per desktop, 4,2 per desktop, per Servizi Terminal 4,1


  > [!IMPORTANT]

  > Il supporto è terminato. Vedere le indicazioni sulla migrazione seguenti.
products:
- windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Original Release
  startDate: 05/25/2007
  endDate: 07/11/2017
content: "\n## <a name=\"links\"></a>Links \n* [Guida alla migrazione](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Edizioni \n* 4,1 per desktop\n* 4,2 per desktop\n* per Servizi Terminal 4,1"
