### YamlMime:Lifecycle
metadata:
  title: ' SoftGrid Application Virtualization'
  description: SoftGrid Application Virtualization segue i criteri fissi relativi al ciclo di vita.
  ms.date: 09/10/2020
  keywords: '4.1 for Desktops,4.2 for Desktops,for Terminal Services 4.1'
name: ' SoftGrid Application Virtualization'
summary: |
  SoftGrid Application Virtualization segue i criteri [fissi](/lifecycle/policies/fixed) relativi al ciclo di vita.

  Questo articolo si riferisce alle seguenti edizioni: 4.1 per Desktop, 4.2 per Desktop e per Servizi terminal 4.1

  > [!IMPORTANT]
  > Il supporto è terminato. Vedere le linee guida per la migrazione riportate di seguito.
products:
  - windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
  - version: Original Release
    startDate: 05/25/2007
    endDate: 07/11/2017
content: |

  ## <a name="links"></a>Collegamenti 
  * [Indicazioni sulla migrazione](https://technet.microsoft.com/en-us/windows/bb899442)


  ## <a name="editions"></a>Edizioni 
  * 4.1 per Desktop
  * 4.2 per Desktop
  * per Servizi terminal 4.1