### YamlMime:Lifecycle
metadata:
  title: " SoftGrid Application Virtualization"
  description: SoftGrid Application Virtualization segue i criteri fissi relativi al ciclo di vita.
  ms.date: 07/28/2020
  ms.openlocfilehash: 17b8078138b718a634c2561ac4b1e73f3966ce24
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: HT
  ms.contentlocale: it-IT
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "824122"
name: " SoftGrid Application Virtualization"
summary: >
  SoftGrid Application Virtualization segue i criteri [fissi](/lifecycle/policies/fixed) relativi al ciclo di vita.


  Questo articolo si riferisce alle seguenti edizioni: 4.1 per Desktop, 4.2 per Desktop e per Servizi terminal 4.1


  > [!IMPORTANT]

  > Il supporto è terminato. Vedere le linee guida per la migrazione riportate di seguito.
products:
- windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Original Release
  startDate: 05/25/2007
  endDate: 07/11/2017
content: "\n## <a name=\"links\"></a>Collegamenti \n* [Indicazioni sulla migrazione](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Edizioni \n* 4.1 per Desktop\n* 4.2 per Desktop\n* per Servizi terminal 4.1"
